# ./docker-compose.yml
version: '2'
# maintainer: TIAGO FACCO <thifacco@gmail.com>

### Networks setup ######################################################

networks: 
   app-tier:
      driver: bridge

### Volumes setup ######################################################

volumes: 
   phpfpm:
   nginx:
   mysql:

### Volumes setup ######################################################

services:

### PHP-FPM ############################################################

   phpfpm:
      image: 'bitnami/php-fpm:latest'
      networks:
         - app-tier
      volumes:
         - ../:/app

### NGINX Server #######################################################
   
   nginx:
      image: 'bitnami/nginx:latest'
      depends_on:
         - phpfpm
      networks:
         - app-tier
      ports:
         - "5000:5000"
         - "6000:6000"
         - "443:443"
      volumes:
         - ./nginx/sites/:/opt/bitnami/nginx/conf/server_blocks

### MYSQL ####################################################
   
   # mysql:
   #    image: mysql:5.7.29
   #    volumes:
   #       - mysql:/var/lib/mysql
   #    environment:
   #       - MYSQL_ROOT_PASSWORD=a8153ef12499f2a0
   #       - MYSQL_DATABASE=chatbot_api
   #       - MYSQL_USER=root
   #       - MYSQL_PASSWORD=a8153ef12499f2a0
   #    ports:
   #       - "3307:3306"
   #    networks:
   #       - app-tier

### MYSQL ####################################################
   
   mysql:
      image: mysql:5.7.29
      volumes:
         - mysql:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=a8153ef12499f2a0
         - MYSQL_DATABASE=cardapp_api
         - MYSQL_USER=root
         - MYSQL_PASSWORD=a8153ef12499f2a0
      ports:
         - "3307:3306"
      networks:
         - app-tier

### MY ADMIN ####################################################
   
   myadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
         - '8080:80'
      environment:
         PMA_HOST: mysql
      networks:
         - app-tier